// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jrTMD9PtzUHtR4vdZtwvoL1UwmNm3Ts',
    appId: '1:933796455972:web:139d004bc6e9051051dab1',
    messagingSenderId: '933796455972',
    projectId: 'inventorymanager-70664',
    authDomain: 'inventorymanager-70664.firebaseapp.com',
    storageBucket: 'inventorymanager-70664.firebasestorage.app',
    measurementId: 'G-JBHR4VZDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATs4i13-cPKeqjvABdeAb3VRtQJfUvThw',
    appId: '1:933796455972:android:229a54e0147cd1e051dab1',
    messagingSenderId: '933796455972',
    projectId: 'inventorymanager-70664',
    storageBucket: 'inventorymanager-70664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylqRkE77p7h3_ifZN7kY8ednLkA1b7-s',
    appId: '1:933796455972:ios:d64a0720539e0d6851dab1',
    messagingSenderId: '933796455972',
    projectId: 'inventorymanager-70664',
    storageBucket: 'inventorymanager-70664.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDylqRkE77p7h3_ifZN7kY8ednLkA1b7-s',
    appId: '1:933796455972:ios:d64a0720539e0d6851dab1',
    messagingSenderId: '933796455972',
    projectId: 'inventorymanager-70664',
    storageBucket: 'inventorymanager-70664.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_jrTMD9PtzUHtR4vdZtwvoL1UwmNm3Ts',
    appId: '1:933796455972:web:bcbe6f3e5b87119551dab1',
    messagingSenderId: '933796455972',
    projectId: 'inventorymanager-70664',
    authDomain: 'inventorymanager-70664.firebaseapp.com',
    storageBucket: 'inventorymanager-70664.firebasestorage.app',
    measurementId: 'G-1TPEGSMDP4',
  );
}
